
admin:
  build: ./admin
  volumes:
    - ./admin/app:/opt/admin
    - ./haproxy/unix-sock:/var/run/
  command:
    - app.py


nginx:
  build: ./nginx
  volumes:
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   - ./nginx/html:/usr/share/nginx/html/
   - ./nginx/server.key:/etc/pki/nginx/private/server.key
   - ./nginx/server.crt:/etc/pki/nginx/server.crt
   - /var/log/nginx:/var/log/nginx
  links:
    - admin:admin

haproxy:
  image: rafpe/docker-haproxy-rsyslog
  volumes:
   - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
   - /var/log/haproxy:/var/log/haproxy
   - ./haproxy/syslog.conf:/etc/rsyslog.d/haproxy.conf
   - ./haproxy/unix-sock:/opt/haproxy/
  ports:
   - 443:443
  links:
   - ssr
   - nginx

ssr:
  build: ./ssr 
  ports:
   - 51234:51243
